[xkb_config]
rules = ""
model = ""
layout = "us"
variant = ""
options = ""

[input_default]
acceleration_profile = "Adaptive"
click_method = "ButtonAreas"
disable_while_typing = false
left_handed = false
middle_emulation = false
rotation_angle = 0
scroll_factor = 1.0
scroll_method = "TwoFinger"
tap_button_map = "LeftRightMiddle"
tap_drag = true
tap_drag_lock = false
tap_enabled = true

[workspaces]
workspace_layout = "Horizontal"
workspace_amount = 4

[cosmic_comp]
resize_mode = "Smart"
resize_indicator = "Lines"

[autotile]
enable = false

[focus_follows_cursor]
enable = false

[cursor_follows_focus]
enable = false